/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.78
 * Generated at: 2023-04-01 13:39:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import in.co.rays.project_3.util.DataUtility;
import in.co.rays.project_3.util.ServletUtility;
import in.co.rays.project_3.controller.GetMarksheetCtl;
import in.co.rays.project_3.controller.ORSView;
import in.co.rays.project_3.controller.LoginCtl;
import in.co.rays.project_3.controller.ORSView;
import in.co.rays.project_3.controller.LoginCtl;
import in.co.rays.project_3.dto.RoleDTO;
import in.co.rays.project_3.dto.UserDTO;
import in.co.rays.project_3.controller.ORSView;

public final class GetMarksheetView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/jsp/Header.jsp", Long.valueOf(1680353511239L));
    _jspx_dependants.put("/jsp/FooterView.jsp", Long.valueOf(1680353553651L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("in.co.rays.project_3.controller.GetMarksheetCtl");
    _jspx_imports_classes.add("in.co.rays.project_3.util.ServletUtility");
    _jspx_imports_classes.add("in.co.rays.project_3.dto.RoleDTO");
    _jspx_imports_classes.add("in.co.rays.project_3.util.DataUtility");
    _jspx_imports_classes.add("in.co.rays.project_3.controller.LoginCtl");
    _jspx_imports_classes.add("in.co.rays.project_3.dto.UserDTO");
    _jspx_imports_classes.add("in.co.rays.project_3.controller.ORSView");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<title>Get Marksheet View</title>\n");
      out.write("<script src=\"");
      out.print(ORSView.APP_CONTEXT);
      out.write("/js/jquery.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\"\n");
      out.write("	src=\"");
      out.print(ORSView.APP_CONTEXT);
      out.write("/js/CheckBox11.js\"></script>\n");
      out.write("<style>\n");
      out.write(".p1 {\n");
      out.write("	padding: 5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".text {\n");
      out.write("	text-align: center;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#po1 {\n");
      out.write("	font-size: 18px;\n");
      out.write("	text-align: center;\n");
      out.write("	height: 30px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("body {\n");
      out.write("	background-image: url('");
      out.print(ORSView.APP_CONTEXT);
      out.write("/img/img33.jpg');\n");
      out.write("	background-repeat: no-repeat;\n");
      out.write("	background-attachment: fixed; \n");
      out.write("	background-size: cover;\n");
      out.write("	padding-top: 180px;\n");
      out.write("	\n");
      out.write("/* 	background-size: 100%; */\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<div>\n");
      out.write("		");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<title>Header</title>\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"https://use.fontawesome.com/releases/v5.6.3/css/all.css\"\n");
      out.write("	integrity=\"sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/\"\n");
      out.write("	crossorigin=\"anonymous\">\n");
      out.write("\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css\">\n");
      out.write("<script\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\n");
      out.write("<script\n");
      out.write("	src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\n");
      out.write("<script\n");
      out.write("	src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("<style type=\"text/css\">\n");
      out.write(".raj {\n");
      out.write("	background-image: linear-gradient(to bottom right,grey,white);\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	");

		UserDTO userDto = (UserDTO) session.getAttribute("user");

		boolean userLoggedIn = userDto != null;	

		String welcomeMsg = "Hi, ";

		if (userLoggedIn) {
			String role = (String) session.getAttribute("role");
			welcomeMsg += userDto.getFirstName() + " (" + role + ")";
		} else {
			welcomeMsg += "Guest"; 
		}
	
      out.write("\n");
      out.write("	<div class=\"header\">\n");
      out.write("		<nav class=\"navbar navbar-expand-lg fixed-top raj\"> <a\n");
      out.write("			class=\"navbar-brand\" href=\"");
      out.print(ORSView.WELCOME_CTL);
      out.write("\"><img\n");
      out.write("			src=\"");
      out.print(ORSView.APP_CONTEXT);
      out.write("/img/custom.png\" width=\"190px\"\n");
      out.write("			height=\"50px\"></a>\n");
      out.write("		<button class=\"navbar-toggler \" type=\"button\" data-toggle=\"collapse\"\n");
      out.write("			data-target=\"#navbarNav\" aria-controls=\"navbarNav\"\n");
      out.write("			aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("			<span class=\"navbar-toggler-icon\"> <i class=\"fa fa-bars\"\n");
      out.write("				style=\"color: #fff; font-size: 28px;\"></i></span>\n");
      out.write("		</button>\n");
      out.write("		<div class=\"collapse navbar-collapse\" id=\"navbarNav\">\n");
      out.write("			<ul class=\"nav navbar-nav ml-auto\">\n");
      out.write("				<a class=\"nav-link\" href=\"#\"> <span class=\"sr-only\">(current)</span>\n");
      out.write("				</a>\n");
      out.write("				");

					if (userLoggedIn) {
				
      out.write("\n");
      out.write("				\n");
      out.write("				\n");
      out.write("			\n");
      out.write("				\n");
      out.write("				");

					if (userDto.getRoleId() == RoleDTO.STUDENT) {
				
      out.write("\n");
      out.write("\n");
      out.write("				<li class=\"nav-item dropdown\" style=\"padding-left: 5px\"><a\n");
      out.write("					class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\n");
      out.write("					role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\n");
      out.write("					aria-expanded=\"false\"> <font style=\"color: white;\">College</font>\n");
      out.write("				</a>\n");
      out.write("					<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\n");
      out.write("						<a class=\"dropdown-item\" href=\"");
      out.print(ORSView.COLLEGE_CTL);
      out.write("\"><i\n");
      out.write("							class=\"fa fa-university\"></i>Add College</a> <a class=\"dropdown-item\"\n");
      out.write("							href=\"");
      out.print(ORSView.COLLEGE_LIST_CTL);
      out.write("\"><i\n");
      out.write("							class=\"fa fa-building\"></i>College List </a>\n");
      out.write("					</div></li>\n");
      out.write("				<li class=\"nav-item dropdown\" style=\"padding-left: 5px\"><a\n");
      out.write("					class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\n");
      out.write("					role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\n");
      out.write("					aria-expanded=\"false\"> <font style=\"color: white;\">Course\n");
      out.write("					</font></a>\n");
      out.write("					<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\n");
      out.write("						<a class=\"dropdown-item\" href=\"");
      out.print(ORSView.COURSE_CTL);
      out.write("\"><i\n");
      out.write("							class=\"fa fa-book-open\"></i>Add Course</a> <a class=\"dropdown-item\"\n");
      out.write("							href=\"");
      out.print(ORSView.COURSE_LIST_CTL);
      out.write("\"><i\n");
      out.write("							class=\"fa fa-sort-amount-down\"></i>Course List </a>\n");
      out.write("					</div></li>\n");
      out.write("				<li class=\"nav-item dropdown\" style=\"padding-left: 5px\"><a\n");
      out.write("					class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\n");
      out.write("					role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\n");
      out.write("					aria-expanded=\"false\"> <font style=\"color: white;\">Student</font>\n");
      out.write("				</a>\n");
      out.write("					<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\n");
      out.write("						<a class=\"dropdown-item\" href=\"");
      out.print(ORSView.STUDENT_CTL);
      out.write("\"><i\n");
      out.write("							class=\"fa fa-user-circle\"></i>Add Student</a> <a\n");
      out.write("							class=\"dropdown-item\" href=\"");
      out.print(ORSView.STUDENT_LIST_CTL);
      out.write("\"><i\n");
      out.write("							class=\"fa fa-users\"></i>Student List</a>\n");
      out.write("					</div></li>\n");
      out.write("				<li class=\"nav-item dropdown\" style=\"padding-left: 5px\"><a\n");
      out.write("					class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\n");
      out.write("					role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\n");
      out.write("					aria-expanded=\"false\"> <font style=\"color: white;\">Faculty\n");
      out.write("					</font></a>\n");
      out.write("					<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\n");
      out.write("						<a class=\"dropdown-item\" href=\"");
      out.print(ORSView.FACULTY_CTL);
      out.write("\"><i\n");
      out.write("							class=\"fa fa-user-tie\"></i>Add Faculty</a> <a class=\"dropdown-item\"\n");
      out.write("							href=\"");
      out.print(ORSView.FACULTY_LIST_CTL);
      out.write("\"><i class=\" fa fa-users\"></i>Faculty\n");
      out.write("							List</a>\n");
      out.write("					</div></li>\n");
      out.write("\n");
      out.write("				<li class=\"nav-item dropdown\" style=\"padding-left: 5px\"><a\n");
      out.write("					class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\n");
      out.write("					role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\n");
      out.write("					aria-expanded=\"false\"> <font style=\"color: white;\">Time\n");
      out.write("							Table</font>\n");
      out.write("				</a>\n");
      out.write("					<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\n");
      out.write("						<a class=\"dropdown-item\" href=\"");
      out.print(ORSView.TIMETABLE_CTL);
      out.write("\"><i\n");
      out.write("							class=\"fa fa-clock\"></i>Add TimeTable</a> <a class=\"dropdown-item\"\n");
      out.write("							href=\"");
      out.print(ORSView.TIMETABLE_LIST_CTL);
      out.write("\"><i class=\"fa fa-clock\"></i>TimeTable\n");
      out.write("							List</a>\n");
      out.write("					</div></li>\n");
      out.write("				<li class=\"nav-item dropdown\" style=\"padding-left: 5px\"><a\n");
      out.write("					class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\n");
      out.write("					role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\n");
      out.write("					aria-expanded=\"false\"> <font style=\"color: white;\">Subject</font>\n");
      out.write("				</a>\n");
      out.write("					<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\n");
      out.write("						<a class=\"dropdown-item\" href=\"");
      out.print(ORSView.SUBJECT_CTL);
      out.write("\"><i\n");
      out.write("							class=\"fa fa-calculator\"></i>Add Subject</a> <a class=\"dropdown-item\"\n");
      out.write("							href=\"");
      out.print(ORSView.SUBJECT_LIST_CTL);
      out.write("\"> <i\n");
      out.write("							class=\"fa fa-sort-amount-down\"></i>Subject List\n");
      out.write("						</a>\n");
      out.write("					</div></li>\n");
      out.write("\n");
      out.write("\n");
      out.write("				<li class=\"nav-item dropdown\" style=\"padding-left: 5px\"><a\n");
      out.write("					class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\n");
      out.write("					role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\n");
      out.write("					aria-expanded=\"false\"> <font style=\"color: black;\">Marksheet\n");
      out.write("					</font></a>\n");
      out.write("\n");
      out.write("					<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\n");
      out.write("\n");
      out.write("						<a class=\"dropdown-item\" href=\"");
      out.print(ORSView.MARKSHEET_CTL);
      out.write("\"><i\n");
      out.write("							class=\"fa fa-file\"></i>Add Marksheet</a> <a class=\"dropdown-item\"\n");
      out.write("							href=\"");
      out.print(ORSView.MARKSHEET_LIST_CTL);
      out.write("\"><i class=\"fa fa-paste\"></i>Marksheet\n");
      out.write("							List</a> <a class=\"dropdown-item\"\n");
      out.write("							href=\"");
      out.print(ORSView.MARKSHEET_MERIT_LIST_CTL);
      out.write("\"><i\n");
      out.write("							class=\" fa fa-file-alt\"></i>Marksheet Merit List </a> <a\n");
      out.write("							class=\"dropdown-item\" href=\"");
      out.print(ORSView.GET_MARKSHEET_CTL);
      out.write("\"><i\n");
      out.write("							class=\"fa fa-copy\"></i>Get Marksheet</a>\n");
      out.write("					</div></li>\n");
      out.write("				");

					} else if (userDto.getRoleId() == RoleDTO.ADMIN) {
				
      out.write("\n");
      out.write("\n");
      out.write("				<li class=\"nav-item dropdown\" style=\"padding-left: 5px;\"><a\n");
      out.write("					class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\n");
      out.write("					role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\n");
      out.write("					aria-expanded=\"false\"> <font style=\"color: black;\">User</font>\n");
      out.write("				</a>\n");
      out.write("					<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\n");
      out.write("						<a class=\"dropdown-item\" href=\"");
      out.print(ORSView.USER_CTL);
      out.write("\"><i\n");
      out.write("							class=\"fa fa-user-circle\"></i>Add User</a> <a class=\"dropdown-item\"\n");
      out.write("							href=\"");
      out.print(ORSView.USER_LIST_CTL);
      out.write("\"><i\n");
      out.write("							class=\"fa fa-user-friends\"></i>User List</a>\n");
      out.write("					</div></li>\n");
      out.write("\n");
      out.write("				<li class=\"nav-item dropdown\" style=\"padding-left: 5px\"><a\n");
      out.write("					class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\n");
      out.write("					role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\n");
      out.write("					aria-expanded=\"false\"> <font style=\"color: black;\">Marksheet\n");
      out.write("					</font></a>\n");
      out.write("\n");
      out.write("					<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\n");
      out.write("\n");
      out.write("						<a class=\"dropdown-item\" href=\"");
      out.print(ORSView.MARKSHEET_CTL);
      out.write("\"><i\n");
      out.write("							class=\"fa fa-file\"></i>Add Marksheet</a> <a class=\"dropdown-item\"\n");
      out.write("							href=\"");
      out.print(ORSView.MARKSHEET_LIST_CTL);
      out.write("\"><i class=\"fa fa-paste\"></i>Marksheet\n");
      out.write("							List</a> <a class=\"dropdown-item\"\n");
      out.write("							href=\"");
      out.print(ORSView.MARKSHEET_MERIT_LIST_CTL);
      out.write("\"><i\n");
      out.write("							class=\" fa fa-file-alt\"></i>Marksheet Merit List </a> <a\n");
      out.write("							class=\"dropdown-item\" href=\"");
      out.print(ORSView.GET_MARKSHEET_CTL);
      out.write("\"><i\n");
      out.write("							class=\"fa fa-copy\"></i>Get Marksheet</a>\n");
      out.write("					</div></li>\n");
      out.write("\n");
      out.write("				<li class=\"nav-item dropdown\" style=\"padding-left: 5px\"><a\n");
      out.write("					class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\n");
      out.write("					role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\n");
      out.write("					aria-expanded=\"false\"> <font style=\"color: black;\">Role</font>\n");
      out.write("				</a>\n");
      out.write("					<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\n");
      out.write("						<a class=\"dropdown-item\" href=\"");
      out.print(ORSView.ROLE_CTL);
      out.write("\"><i\n");
      out.write("							class=\"fa fa-user-tie\"></i>Add Role</a> <a class=\"dropdown-item\"\n");
      out.write("							href=\"");
      out.print(ORSView.ROLE_LIST_CTL);
      out.write("\"><i\n");
      out.write("							class=\"fa fa-user-friends\"></i>Role List</a>\n");
      out.write("					</div></li>\n");
      out.write("				<li class=\"nav-item dropdown\" style=\"padding-left: 5px\"><a\n");
      out.write("					class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\n");
      out.write("					role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\n");
      out.write("					aria-expanded=\"false\"> <font style=\"color: black;\">College</font>\n");
      out.write("				</a>\n");
      out.write("					<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\n");
      out.write("						<a class=\"dropdown-item\" href=\"");
      out.print(ORSView.COLLEGE_CTL);
      out.write("\"><i\n");
      out.write("							class=\"fa fa-university\"></i>Add College</a> <a class=\"dropdown-item\"\n");
      out.write("							href=\"");
      out.print(ORSView.COLLEGE_LIST_CTL);
      out.write("\"><i\n");
      out.write("							class=\"fa fa-building\"></i>College List </a>\n");
      out.write("					</div></li>\n");
      out.write("				<li class=\"nav-item dropdown\" style=\"padding-left: 5px\"><a\n");
      out.write("					class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\n");
      out.write("					role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\n");
      out.write("					aria-expanded=\"false\"> <font style=\"color: black;\">Course\n");
      out.write("					</font></a>\n");
      out.write("					<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\n");
      out.write("						<a class=\"dropdown-item\" href=\"");
      out.print(ORSView.COURSE_CTL);
      out.write("\"><i\n");
      out.write("							class=\"fa fa-book-open\"></i>Add Course</a> <a class=\"dropdown-item\"\n");
      out.write("							href=\"");
      out.print(ORSView.COURSE_LIST_CTL);
      out.write("\"><i\n");
      out.write("							class=\"fa fa-sort-amount-down\"></i>Course List </a>\n");
      out.write("					</div></li>\n");
      out.write("				<li class=\"nav-item dropdown\" style=\"padding-left: 5px\"><a\n");
      out.write("					class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\n");
      out.write("					role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\n");
      out.write("					aria-expanded=\"false\"> <font style=\"color: black;\">Student</font>\n");
      out.write("				</a>\n");
      out.write("					<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\n");
      out.write("						<a class=\"dropdown-item\" href=\"");
      out.print(ORSView.STUDENT_CTL);
      out.write("\"><i\n");
      out.write("							class=\"fa fa-user-circle\"></i>Add Student</a> <a\n");
      out.write("							class=\"dropdown-item\" href=\"");
      out.print(ORSView.STUDENT_LIST_CTL);
      out.write("\"><i\n");
      out.write("							class=\"fa fa-users\"></i>Student List</a>\n");
      out.write("					</div></li>\n");
      out.write("				<li class=\"nav-item dropdown\" style=\"padding-left: 5px\"><a\n");
      out.write("					class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\n");
      out.write("					role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\n");
      out.write("					aria-expanded=\"false\"> <font style=\"color: black;\">Faculty\n");
      out.write("					</font></a>\n");
      out.write("					<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\n");
      out.write("						<a class=\"dropdown-item\" href=\"");
      out.print(ORSView.FACULTY_CTL);
      out.write("\"><i\n");
      out.write("							class=\"fa fa-user-tie\"></i>Add Faculty</a> <a class=\"dropdown-item\"\n");
      out.write("							href=\"");
      out.print(ORSView.FACULTY_LIST_CTL);
      out.write("\"><i class=\" fa fa-users\"></i>Faculty\n");
      out.write("							List</a>\n");
      out.write("					</div></li>\n");
      out.write("\n");
      out.write("				<li class=\"nav-item dropdown\" style=\"padding-left: 5px\"><a\n");
      out.write("					class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\n");
      out.write("					role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\n");
      out.write("					aria-expanded=\"false\"> <font style=\"color: black;\">Time\n");
      out.write("							Table</font>\n");
      out.write("				</a>\n");
      out.write("					<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\n");
      out.write("						<a class=\"dropdown-item\" href=\"");
      out.print(ORSView.TIMETABLE_CTL);
      out.write("\"><i\n");
      out.write("							class=\"fa fa-clock\"></i>Add TimeTable</a> <a class=\"dropdown-item\"\n");
      out.write("							href=\"");
      out.print(ORSView.TIMETABLE_LIST_CTL);
      out.write("\"><i class=\"fa fa-clock\"></i>TimeTable\n");
      out.write("							List</a>\n");
      out.write("					</div></li>\n");
      out.write("				<li class=\"nav-item dropdown\" style=\"padding-left: 5px\"><a\n");
      out.write("					class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\n");
      out.write("					role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\n");
      out.write("					aria-expanded=\"false\"> <font style=\"color: black;\">Subject</font>\n");
      out.write("				</a>\n");
      out.write("					<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\n");
      out.write("						<a class=\"dropdown-item\" href=\"");
      out.print(ORSView.SUBJECT_CTL);
      out.write("\"><i\n");
      out.write("							class=\"fa fa-calculator\"></i>Add Subject</a> <a class=\"dropdown-item\"\n");
      out.write("							href=\"");
      out.print(ORSView.SUBJECT_LIST_CTL);
      out.write("\"> <i\n");
      out.write("							class=\"fa fa-sort-amount-down\"></i>Subject List\n");
      out.write("						</a>\n");
      out.write("					</div></li>\n");
      out.write("\n");
      out.write("				");

					}
					}
				
      out.write("\n");
      out.write("				<li class=\"nav-item dropdown\"\n");
      out.write("					style=\"padding-left: 5px; padding-right: 97px\"><a\n");
      out.write("					class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\n");
      out.write("					role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\n");
      out.write("					aria-expanded=\"false\"><font style=\"color: black;\">");
      out.print(welcomeMsg);
      out.write("\n");
      out.write("					</font></a>\n");
      out.write("					<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\n");
      out.write("						");

							if (userLoggedIn) {
						
      out.write("\n");
      out.write("						<a class=\"dropdown-item\"\n");
      out.write("							href=\"");
      out.print(ORSView.LOGIN_CTL);
      out.write("?operation=");
      out.print(LoginCtl.OP_LOG_OUT);
      out.write("\"><i\n");
      out.write("							class=\"fa fa-sign-out-alt\"></i>Logout </a> <a class=\"dropdown-item\"\n");
      out.write("							href=\"");
      out.print(ORSView.MY_PROFILE_CTL);
      out.write("\"><i class=\"fa fa-user-tie\"></i>My\n");
      out.write("							Profile</a> <a class=\"dropdown-item\"\n");
      out.write("							href=\"");
      out.print(ORSView.CHANGE_PASSWORD_CTL);
      out.write("\"> <i\n");
      out.write("							class=\"fa fa-edit\"></i>Change Password\n");
      out.write("						</a> <a class=\"dropdown-item\" target=\"blank\"\n");
      out.write("							href=\"");
      out.print(ORSView.JAVA_DOC_VIEW);
      out.write("\"><i class=\"fa fa-clone\"></i>Java\n");
      out.write("							Doc </a>\n");
      out.write("						");

							} else {
						
      out.write("\n");
      out.write("						<a class=\"dropdown-item\" href=\"");
      out.print(ORSView.LOGIN_CTL);
      out.write("\"><i\n");
      out.write("							class=\"fa fa-sign-in-alt\">Login</i> <a class=\"dropdown-item\"\n");
      out.write("							href=\"");
      out.print(ORSView.USER_REGISTRATION_CTL);
      out.write("\"><i\n");
      out.write("								class=\"fa fa-registered\"></i> User Registration</a>\n");
      out.write("					</div></li>\n");
      out.write("				");

					}
				
      out.write("\n");
      out.write("			</ul>\n");
      out.write("		</div>\n");
      out.write("		</nav>\n");
      out.write("	</div>\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("	</div>\n");
      out.write("	<div>\n");
      out.write("		<form action=\"");
      out.print(ORSView.GET_MARKSHEET_CTL);
      out.write("\" method=\"post\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("			<div align=\"center\">\n");
      out.write("				<h1 style=\"font-size: 40px; padding-top: 24px; color: #162390;\">Get\n");
      out.write("					Marksheet</h1>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"row\">\n");
      out.write("				<div class=\"col-md-4\"></div>\n");
      out.write("\n");
      out.write("				");

					if (!ServletUtility.getSuccessMessage(request).equals("")) {
				
      out.write("\n");
      out.write("\n");
      out.write("				<div class=\"col-md-4 alert alert-success alert-dismissible\"\n");
      out.write("					style=\"background-color: #80ff80\">\n");
      out.write("					<button type=\"button\" class=\"close\" data-dismiss=\"alert\">&times;</button>\n");
      out.write("					<h4>\n");
      out.write("						<font color=\"#008000\">");
      out.print(ServletUtility.getSuccessMessage(request));
      out.write("</font>\n");
      out.write("					</h4>\n");
      out.write("				</div>\n");
      out.write("				");

					}
				
      out.write("\n");
      out.write("\n");
      out.write("				<div class=\"col-md-4\"></div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"row\">\n");
      out.write("				<div class=\"col-md-4\"></div>\n");
      out.write("\n");
      out.write("				");

					if (!ServletUtility.getErrorMessage(request).equals("")) {
				
      out.write("\n");
      out.write("				<div class=\" col-md-4 alert alert-danger alert-dismissible\">\n");
      out.write("					<button type=\"button\" class=\"close\" data-dismiss=\"alert\">&times;</button>\n");
      out.write("					<h4>\n");
      out.write("						<font color=\"red\">");
      out.print(ServletUtility.getErrorMessage(request));
      out.write("</font>\n");
      out.write("					</h4>\n");
      out.write("				</div>\n");
      out.write("				");

					}
				
      out.write("\n");
      out.write("				<div class=\"col-md-4\"></div>\n");
      out.write("			</div>\n");
      out.write("			");
      in.co.rays.project_3.dto.MarksheetDTO dto = null;
      dto = (in.co.rays.project_3.dto.MarksheetDTO) _jspx_page_context.getAttribute("dto", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (dto == null){
        dto = new in.co.rays.project_3.dto.MarksheetDTO();
        _jspx_page_context.setAttribute("dto", dto, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\n");
      out.write("			</br>\n");
      out.write("			<div class=\"row\">\n");
      out.write("				<div class=\"col-md-4\"></div>\n");
      out.write("				<span style=\"margin-left: 15px\"><b>Roll No:</b></span>\n");
      out.write("				<div class=\"col-md-2\">\n");
      out.write("					<input type=\"text\" name=\"rollNo\" class=\"form-control\"\n");
      out.write("						placeholder=\"Enter Roll Number\"\n");
      out.write("						value=\"");
      out.print(ServletUtility.getParameter("rollNo", request));
      out.write("\">&emsp;\n");
      out.write("				</div>\n");
      out.write("				<div class=\"col-md-2\">\n");
      out.write("					<input type=\"submit\" class=\"btn btn-primary btn-md\"\n");
      out.write("						style=\"font-size: 17px\" name=\"operation\"\n");
      out.write("						value=\"");
      out.print(GetMarksheetCtl.OP_GO);
      out.write("\">&emsp;<font color=\"red\">");
      out.print(ServletUtility.getErrorMessage("rollNo", request));
      out.write("</font>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"col-md-4\"></div>\n");
      out.write("\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			");

				if (dto.getRollNo() != null && dto.getRollNo().trim().length() > 0) {
			
      out.write("\n");
      out.write("		\n");
      out.write("	</div>\n");
      out.write("	<div class=\"container\">\n");
      out.write("\n");
      out.write("		<table width=\"100%\" style=\"background-color: white;\" border=\"2px\">\n");
      out.write("			<tr>\n");
      out.write("				<th id=\"po1\" colspan=\"2\">RollNo</th>\n");
      out.write("				<td id=\"po1\" align=\"center\" colspan=\"3\">");
      out.print(DataUtility.getStringData(dto.getRollNo()));
      out.write("</td>\n");
      out.write("			</tr>\n");
      out.write("			<tr>\n");
      out.write("				<th id=\"po1\" colspan=\"2\">Name</th>\n");
      out.write("				<td id=\"po1\" align=\"center\" colspan=\"3\">");
      out.print(DataUtility.getStringData(dto.getName()));
      out.write("</td>\n");
      out.write("			</tr>\n");
      out.write("			<tr style=\"background-color: #e1b5158c;\">\n");
      out.write("				<th id=\"po1\">Subject</th>\n");
      out.write("				<th id=\"po1\">Max Marks</th>\n");
      out.write("				<th id=\"po1\">Min Marks</th>\n");
      out.write("				<th id=\"po1\" colspan=\"2\">Marks Obtain</th>\n");
      out.write("			</tr>\n");
      out.write("			<tr>\n");
      out.write("				<td colspan=\"3\"></td>\n");
      out.write("				<th id=\"po1\">Marks</th>\n");
      out.write("				<th style=\"color: blue;\" id=\"po1\">Grade</th>\n");
      out.write("			</tr>\n");
      out.write("			<tr>\n");
      out.write("				<th id=\"po1\">Physics</th>\n");
      out.write("				<td align=\"center\">100</td>\n");
      out.write("				<td align=\"center\">35</td>\n");
      out.write("				<td id=\"po1\" align=\"center\">");
      out.print(DataUtility.getStringData(String.valueOf(dto.getPhysics())));
      out.write("\n");
      out.write("					");

						float physics = dto.getPhysics();
							if (dto.getPhysics() < 35) {
					
      out.write("<span style=\"color: red;\">*</span> ");

 	}
 
      out.write("</td>\n");
      out.write("				<td align=\"center\">\n");
      out.write("					");

						if (physics >= 90) {
					
      out.write(" <b>A++</b> ");

 	} else if (physics >= 80) {
 
      out.write(" <b>A</b> ");

 	} else if (physics >= 70) {
 
      out.write(" <b>B++</b> ");

 	} else if (physics >= 60) {
 
      out.write(" <b>B</b> ");

 	} else if (physics >= 50) {
 
      out.write(" <b>C++</b> ");

 	} else if (physics >= 40) {
 
      out.write(" <b>C</b> ");

 	} else if (physics >= 35) {
 
      out.write(" <b>D</b> ");

 	} else if (physics >= 0) {
 
      out.write(" <font color=\"red\"><b>F</b></font> ");

 	}
 
      out.write("\n");
      out.write("				</td>\n");
      out.write("			</tr>\n");
      out.write("			<tr>\n");
      out.write("				<th id=\"po1\">Chemistry</th>\n");
      out.write("				<td align=\"center\">100</td>\n");
      out.write("				<td align=\"center\">35</td>\n");
      out.write("				<td id=\"po1\" align=\"center\">");
      out.print(DataUtility.getStringData(String.valueOf(dto.getChemistry())));
      out.write("\n");
      out.write("					");

						float chemistry = dto.getChemistry();
							if (dto.getChemistry() < 35) {
					
      out.write("<span style=\"color: red;\">*</span> ");

 	}
 
      out.write("</td>\n");
      out.write("				<td align=\"center\">\n");
      out.write("					");

						if (chemistry >= 90) {
					
      out.write(" <b>A++</b> ");

 	} else if (chemistry >= 80) {
 
      out.write(" <b>A</b> ");

 	} else if (chemistry >= 70) {
 
      out.write(" <b>B++</b> ");

 	} else if (chemistry >= 60) {
 
      out.write(" <b>B</b> ");

 	} else if (chemistry >= 50) {
 
      out.write(" <b>C++</b> ");

 	} else if (chemistry >= 40) {
 
      out.write(" <b>C</b> ");

 	} else if (chemistry >= 35) {
 
      out.write(" <b>D</b> ");

 	} else if (chemistry >= 0) {
 
      out.write(" <font color=\"red\"><b>F</b></font> ");

 	}
 
      out.write("\n");
      out.write("				</td>\n");
      out.write("			</tr>\n");
      out.write("			<tr>\n");
      out.write("				<th id=\"po1\">Maths</th>\n");
      out.write("				<td align=\"center\">100</td>\n");
      out.write("				<td align=\"center\">35</td>\n");
      out.write("				<td id=\"po1\" align=\"center\">");
      out.print(DataUtility.getStringData(String.valueOf(dto.getMaths())));
      out.write("\n");
      out.write("					");

						float marks = dto.getMaths();
							if (marks <= 35) {
					
      out.write("<span style=\"color: red;\">*</span> ");

 	}
 
      out.write("</td>\n");
      out.write("				<td align=\"center\">\n");
      out.write("					");

						if (marks >= 90) {
					
      out.write(" <b>A++</b> ");

 	} else if (marks >= 80) {
 
      out.write(" <b>A</b> ");

 	} else if (marks >= 70) {
 
      out.write(" <b>B++</b> ");

 	} else if (marks >= 60) {
 
      out.write(" <b>B</b> ");

 	} else if (marks >= 50) {
 
      out.write(" <b>C++</b> ");

 	} else if (marks >= 40) {
 
      out.write(" <b>C</b> ");

 	} else if (marks >= 35) {
 
      out.write(" <b>D</b> ");

 	} else if (marks >= 0) {
 
      out.write(" <font color=\"red\"><b>F</b></font> ");

 	}
 
      out.write("\n");
      out.write("				</td>\n");
      out.write("\n");
      out.write("			</tr>\n");
      out.write("			<tr>\n");
      out.write("				<th id=\"po1\" colspan=\"2\">Total</th>\n");
      out.write("\n");
      out.write("				<td id=\"po1\" align=\"center\" colspan=\"3\">\n");
      out.write("					");

						int total = ((dto.getMaths()) + (dto.getPhysics()) + (dto.getChemistry()));
							float percentage = (total * 100) / 300;
					
      out.print(total);
      out.write("</td>\n");
      out.write("			</tr>\n");
      out.write("			");

				if ((dto.getMaths() > 35) && (dto.getPhysics() > 35) && (dto.getChemistry() > 35)) {
			
      out.write("\n");
      out.write("			<tr>\n");
      out.write("\n");
      out.write("				<th id=\"po1\" colspan=\"2\">Percentage</th>\n");
      out.write("\n");
      out.write("				<td id=\"po1\" align=\"center\" colspan=\"3\">");
      out.print(percentage);
      out.write("%</td>\n");
      out.write("			</tr>\n");
      out.write("			<tr>\n");
      out.write("				<th id=\"po1\" align=\"center\" colspan=\"2\"><font color=\"blue\">Grade:</font>\n");
      out.write("					");

						if (percentage >= 90) {
					
      out.write(" <b>A++</b> ");

 	} else if (percentage >= 80) {
 
      out.write(" <b>A</b> ");

 	} else if (percentage >= 70) {
 
      out.write(" <b>B++</b> ");

 	} else if (percentage >= 60) {
 
      out.write(" <b>B</b> ");

 	} else if (percentage >= 50) {
 
      out.write(" <b>C++</b> ");

 	} else if (percentage >= 40) {
 
      out.write(" <b>C</b> ");

 	} else if (percentage >= 35) {
 
      out.write(" <b>D</b> ");

 	} else if (percentage >= 0) {
 
      out.write(" <font color=\"red\"><b>F</b></font> ");

 	}
 
      out.write("</th>\n");
      out.write("				<td id=\"po1\" align=\"center\" colspan=\"3\">\n");
      out.write("					");

						if (percentage >= 35) {
					
      out.write(" <font color=\"green\"><b>PASS</b></font> ");

 	}
 
      out.write("\n");
      out.write("				</td>\n");
      out.write("			</tr>\n");
      out.write("			");

				} else {
			
      out.write("\n");
      out.write("			<tr>\n");
      out.write("				<th id=\"po1\" align=\"center\" colspan=\"2\"><font color=\"blue\">Final\n");
      out.write("						Grade:</font><font color=\"red\"><b>F</b></font></th>\n");
      out.write("				<td id=\"po1\" align=\"center\" colspan=\"3\"><font color=\"red\"><b>FAIL</b></font></td>\n");
      out.write("			</tr>\n");
      out.write("\n");
      out.write("			");

				}
			
      out.write("\n");
      out.write("		</table>\n");
      out.write("\n");
      out.write("		");

			}
		
      out.write("\n");
      out.write("\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("<div>\n");
      out.write("	");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
      out.write("<style type=\"text/css\">\n");
      out.write("\n");
      out.write(".footer {\n");
      out.write("   position: fixed;\n");
      out.write("   left: 0;\n");
      out.write("   bottom: 0;\n");
      out.write("   width: 100%;\n");
      out.write("/*      background-color: #343a40;\n");
      out.write(" */      color: white;\n");
      out.write("   text-align: center;\n");
      out.write(" background-image:  linear-gradient(to bottom right, grey, black);\n");
      out.write("}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body >\n");
      out.write("<div class=\"footer\">\n");
      out.write("<center>\n");
      out.write("\n");
      out.write("<h5>&copy; RAYS Technologies</h5></center>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
      out.write("\n");
      out.write("</div>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
